# Generated by Django 2.0.7 on 2018-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_place_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_free',
            new_name='is_taken',
        ),
    ]
