# Generated by Django 2.0.7 on 2018-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20180708_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
